### ISSUE TITLE
The runtime situation is a mess

### ISSUE THREAD

**Issue by ericmjonas** [ericmjonas/pywren#40]
There's no programmatic way of knowing which runtime you're using
There's no good way of making sure you don't accidentally try to run a python2 job with the python3 runtime
It's easy to accidentally deploy a broken runtime.

**Comment by etrain** [comment]
`sys.version_info` ?

**Comment by ericmjonas** [comment]
The concern is also being able to answer your question "is X installed?" I think I should try and save the output of `pip freeze` somehow -- https://gist.github.com/ericmjonas/200f6628539dded1fa7aeab46bbadba5

**Comment by shivaram** [comment]
We can also do some checks on the client side by fetching the runtime (or it's metadata)  to figure this out before we hit lambda ?

**Comment by etrain** [comment]
So the problem is that there's a general mis-match between host (client) environment and worker (cloud) environment. The hope is that the host environment is "close enough" that users code will still run on remote environment. IMO the python 2/3 issue is a non-issue because it should be easy to decide that since the client environment is python 2, then the remote environment should be python 2.

I agree that you should make the output of `pip freeze` available to the host. Essentially this is a `provides.txt` (as opposed to `requirements.txt`) but ultimately I'd imagine that users would like to be able to specify what packages they want installed in the cloud. Something like a user-provided `worker-requirements.txt` It seems possible that this could be generated dynamically as part of the pickling process.

**Comment by ericmjonas** [comment]
I've put a little effort into packaging runtimes here : https://github.com/ericmjonas/pywren-runtimes -- we can now stage them, and there's travis integration to test them. The dev cycle is now 1. build 2. commit to git,  invokestravis, which runs some rudimentary checks, 3. deploy. It's still not ideal, and I think @etrain's idea is brilliant, but at least this will prevent me from uploading an obviously broken default runtime.
